import Head from 'next/head'
import NavigationBar from '../components/NavigationBar'

function MainLayout({children}) {
  return (
    <div className="app">
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />
        {children}
      <footer className='h-[10vh] w-full'>
        footer
      </footer>
    </div>
  )
}

export default MainLayout