import React from 'react'
import Head from 'next/head'
import MainLayout from '../../layout/MainLayout'
import Show from '../../components/Show'

function Id({tv}) {
  return (
    <div className="">
        <Head>
            <title>{tv.name}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainLayout>
            <Show show={tv} />
        </MainLayout>
    </div>
  )
}

export const getServerSideProps = async (context) => {
    const BASE_URL = "https://api.themoviedb.org/3/"
    const API_KEY = process.env.NEXT_PUBLIC_API_KEY
    const {params} = context
    const {id} = params

    const res = await fetch(`${BASE_URL}tv/${id}?append_to_response=videos,images,credits,recommendations,similar,external_ids&api_key=${API_KEY}`)
    const tv = await res.json()
 
    return {
        props: {tv}
    }
}

export default Id