import React from 'react'
import Head from 'next/head'
import MainLayout from '../../layout/MainLayout'
import Show from '../../components/Show'
import Modal from '../../components/Modal'
import {useModalState} from '../../store/useStore'

function Id({movie}) {
    const isModalShow = useModalState(state => state.isModalShow)
    const trailerId = movie.videos.results.find(video => video.type === 'Trailer').key

    return (
        <div className="">
            <Head>
                <title>{movie.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                isModalShow &&
                <Modal id={trailerId} />
            }
            <MainLayout>
                <Show show={movie} />
            </MainLayout>
        </div>
    )
}

export const getServerSideProps = async (context) => {
    const BASE_URL = "https://api.themoviedb.org/3/"
    const API_KEY = process.env.NEXT_PUBLIC_API_KEY
    const {params} = context
    const {id} = params

    const res = await fetch(`${BASE_URL}movie/${id}?append_to_response=videos,images,credits,recommendations,similar,external_ids&api_key=${API_KEY}`)
    const movie = await res.json()
 
    return {
        props: {movie}
    }
}

export default Id