import React, {useEffect} from 'react'
import Head from 'next/head'
import MainLayout from '../../layout/MainLayout'
import FilterSort from '../../components/FilterSort'
import Shows from '../../components/Shows'
import PageLayout from '../../layout/PageLayout'
import {useFilterGenreState, useSortState} from '../../store/useStore'

function Movie() {
  const resetFilter = useFilterGenreState(state => state.resetFilter)
  const resetSort = useSortState(state => state.resetSort)
  
  useEffect(() => {
    return () => {
      resetFilter()
      resetSort()
    }
  }, [resetFilter, resetSort])

  return (
    <MainLayout>
      <Head>
          <title>Movies | SkyFlix</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.svg" />
      </Head>
      <PageLayout>
        <FilterSort />
        <Shows />
      </PageLayout>
    </MainLayout>
  )
}

export default Movie